services:
  hydrus-client:
    build:
      context: .
      dockerfile: ./static/build_files/docker/client
    container_name: hydrus_client
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    tmpfs:
      - /tmp #optional for SPEEEEEEEEEEEEEEEEEEEEEEEEED and less disk access
    ports:
      # - EXPOSED_PORT:CONTAINER_PORT
      - 5800:5800   #noVNC
      - 5900:5900   #VNC
      - 45868:45868 #Booru
      - 45869:45869 #API
  hydrus-server:
    build:
      context: .
      dockerfile: ./static/build_files/docker/server/Dockerfile
    container_name: hydrus-server
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    tmpfs:
      - /tmp #optional for SPEEEEEEEEEEEEEEEEEEEEEEEEED and less disk access
    #ports: This should be set in compose.override.yaml